services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    networks:
      dev:

  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    networks:
      prod:

networks:
  prod:
  dev:
